# Generated by Django 6.0.3 on 2026-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
