# Generated by Django 6.0.3 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, help_text='Stripe Price ID (price_...) — auto-synced on save', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, editable=False, help_text='Stripe Product ID (prod_...) — auto-synced on save', max_length=100),
        ),
    ]
