# Generated by Django 6.0.3 on 2026-03-27 20:28

import customiseapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0002_product_stripe_price_id_product_stripe_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, storage=customiseapp.models._firebase_storage, upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='designsubmissionfile',
            name='file',
            field=models.FileField(storage=customiseapp.models._firebase_storage, upload_to='design_submissions/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, storage=customiseapp.models._firebase_storage, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='SendItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('items_description', models.TextField(help_text='Free-text description of the garments/accessories being sent.')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('custom_details', models.TextField(blank=True, help_text='Design brief: placement, method (print/embroidery), colours, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quote Sent'), ('confirmed', 'Confirmed'), ('in_work', 'In Production'), ('shipped', 'Shipped Back'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for the team (not visible to the customer).')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted to the customer in GBP.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('agreed_waiver', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Logged-in user who submitted (null if guest).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_item_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Send Item Request',
                'verbose_name_plural': 'Send Item Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=customiseapp.models._firebase_storage, upload_to='send-item-requests/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customiseapp.senditemrequest')),
            ],
            options={
                'verbose_name': 'Send Item File',
                'verbose_name_plural': 'Send Item Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
