# Generated by Django 6.0.3 on 2026-04-08 18:57

import customiseapp.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0003_alter_carouselslide_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for guest users.', max_length=64)),
                ('colour', models.CharField(blank=True, max_length=80)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('artwork_size', models.CharField(blank=True, help_text='Small / Medium / Large', max_length=20)),
                ('placement', models.CharField(blank=True, help_text='e.g. Front Centre, Back Full', max_length=50)),
                ('printing_side', models.CharField(blank=True, help_text='Front Only / Back Only / Front & Back', max_length=30)),
                ('artwork_file', models.FileField(blank=True, null=True, storage=customiseapp.models._firebase_storage, upload_to='product-customisations/')),
                ('artwork_filename', models.CharField(blank=True, max_length=255)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variant_summary', models.TextField(blank=True)),
                ('fulfilment_status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', help_text='Admin-set production status visible in the dashboard.', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note — not shown to customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customisations', to='customiseapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_customisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Customisation',
                'verbose_name_plural': 'Product Customisations',
                'ordering': ['-created_at'],
            },
        ),
    ]
