# Generated by Django 6.0.3 on 2026-04-09 22:30

import customiseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0004_productcustomisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomisation',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Extra info provided by customer (e.g. party text, font choice).'),
        ),
        migrations.AddField(
            model_name='productcustomisation',
            name='artwork_file_back',
            field=models.FileField(blank=True, help_text="Back artwork — populated only when printing side is 'Front & Back'.", null=True, storage=customiseapp.models._firebase_storage, upload_to='product-customisations/back/'),
        ),
        migrations.AddField(
            model_name='productcustomisation',
            name='artwork_filename_back',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcustomisation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Selected quantity (stickers, party items, etc.).', null=True),
        ),
        migrations.AlterField(
            model_name='productcustomisation',
            name='artwork_file',
            field=models.FileField(blank=True, help_text='Front artwork (or only artwork for single-side products).', null=True, storage=customiseapp.models._firebase_storage, upload_to='product-customisations/'),
        ),
    ]
