# Generated by Django 6.0.3 on 2026-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0005_productcustomisation_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Apparel', 'Apparel'), ('Accessories', 'Accessories'), ('Party Essentials', 'Party Essentials'), ('Stickers & Labels', 'Stickers & Labels'), ('Other', 'Other')], max_length=100),
        ),
    ]
