# Generated by Django 6.0.3 on 2026-05-05 05:52

import customiseapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=customiseapp.models._firebase_storage, upload_to='products/variations/')),
                ('label', models.CharField(blank=True, help_text="Short label shown to customers, e.g. 'Black', 'Navy Blue'.", max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Slot number (1–5). Determines scroll order.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_images', to='customiseapp.product')),
            ],
            options={
                'verbose_name': 'Product Variation Image',
                'verbose_name_plural': 'Product Variation Images',
                'ordering': ['position', 'id'],
            },
        ),
    ]
