# Generated by Django 6.0.3 on 2026-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customiseapp', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customisation_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
